#!/usr/bin/env python3
from bs4 import BeautifulSoup
import sys
from colorama import Fore
import requests as req
import re
import os

package = sys.argv[1]

link = "https://github.com/search?q=" + package + "&type=repositories"

linkget = req.get(link)

soup = BeautifulSoup(linkget.text, 'html.parser')


reposlinks = soup.find("ul", class_="repo-list")

pattern = re.compile(r'href="(.*)">')
lists = re.findall(pattern, str(reposlinks))
i = 0
for x in lists:
    print(Fore.GREEN + str(i)+ "|  " + x)
    i += 1
print(Fore.RESET)
numb = int(input(Fore.BLUE +"Enter number:"))
print(Fore.RESET)
if numb < 0:
    AttributeError()
elif 9999 == numb:
    exit(0)

os.system("git clone https://github.com/" + lists[numb])
